export default {
  login: "Gladson-Samuel-S",
  id: 74543240,
  node_id: "MDQ6VXNlcjc0NTQzMjQw",
  avatar_url: "https://avatars.githubusercontent.com/u/74543240?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Gladson-Samuel-S",
  html_url: "https://github.com/Gladson-Samuel-S",
  followers_url: "https://api.github.com/users/Gladson-Samuel-S/followers",
  following_url:
    "https://api.github.com/users/Gladson-Samuel-S/following{/other_user}",
  gists_url: "https://api.github.com/users/Gladson-Samuel-S/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Gladson-Samuel-S/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/Gladson-Samuel-S/subscriptions",
  organizations_url: "https://api.github.com/users/Gladson-Samuel-S/orgs",
  repos_url: "https://api.github.com/users/Gladson-Samuel-S/repos",
  events_url: "https://api.github.com/users/Gladson-Samuel-S/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Gladson-Samuel-S/received_events",
  type: "User",
  site_admin: false,
  name: "Gladson Samuel S",
  company: null,
  blog: "www.linkedin.com/in/gladson-samuel-283768170",
  location: "India",
  email: null,
  hireable: null,
  bio: "Student | Interested in Web Development and Android App Development.",
  twitter_username: "gladson_samuel",
  public_repos: 12,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2020-11-16T12:06:22Z",
  updated_at: "2021-03-18T15:45:43Z",
}
